add rhessys files
cybergis/Jupyter-xsede pull request #29
Opened 2021-02-16 16:02 UTC by DavidChoi76

added rhessys.py 
update rhessysSupervisor.py
added Dockerfile and Definition file

2021-02-17 15:05 UTC, zhiyuli requested changes
@DavidChoi76 I finished first review of this repo. thanks

2021-02-17 15:05 UTC, zhiyuli commented on cybergis/rhessys.py
> +        self.remote_singularity_img_path = "/home/yc5ef/rhessys_20210201.sif"
@DavidChoi76 we need to change to use path on keeling: 
"/data/keeling/a/cigi-gisolve/simages/rhessys_20210201.sif"

Also, what is the base OS version in your singularity image? ubuntu 18 or 16?

2021-02-17 15:05 UTC, zhiyuli commented on cybergis/rhessys.py
> +        self.remote_singularity_img_path = "/home/yc5ef/rhessys_20210201.sif"
@DavidChoi76  same here. change to comet path: 
"/home/cybergis/SUMMA_IMAGE/rhessys_20210201.sif"

2021-02-17 15:05 UTC, zhiyuli commented on cybergis/rhessys.py
> +    def __init__(
@DavidChoi76 if this function does not override anything in baseclass, we should be able to remove it.

2021-02-17 15:05 UTC, zhiyuli commented on singularity_def/rhessys/Dockerfile_rhessysEC7.2
> +ENV F_MASTER /code
@DavidChoi76 let's clean this up a little bit. Better to remove all SUMMA staff

2021-02-17 15:05 UTC, zhiyuli commented on singularity_def/rhessys/Dockerfile_rhessysEC7.2
> +RUN git clone https://github.com/NCAR/summa.git /tmp/summa \
summa leftover

2021-02-17 15:05 UTC, zhiyuli commented on singularity_def/rhessys/Dockerfile_rhessysEC7.2
> +RUN /opt/miniconda3/bin/python -m pip install --quiet git+https://github.com/DavidChoi76/pyrhessys.git
@DavidChoi76  is this the only lib that needs to be installed for rhessys? it has both PyRhessys and Rhessys binary?

2021-02-17 15:05 UTC, zhiyuli commented on singularity_def/rhessys/Dockerfile_rhessysEC7.2
> +# create a symbolic link to summa.exe being consistent with old summa singularity images
summa leftover

2021-02-17 15:45 UTC, DavidChoi76 commented on cybergis/rhessys.py
> +        self.remote_singularity_img_path = "/home/yc5ef/rhessys_20210201.sif"
I used `ubuntu:xenial` like SUMMA Dockerfile. You can check Dockerfile and Singularity file in https://github.com/cybergis/Jupyter-xsede/tree/rhessys/singularity_def/rhessys

2021-02-18 21:48 UTC, zhiyuli approved these changes

2021-02-18 21:49 UTC, merged